### Mold NND
# 1. EPC Sensor Offset (Shoulder Line or Cutting Height)
[SPEC]
SPEC_TCH_USL = 2.4
SPEC_TCH_REF = 1.7
SPEC_TCH_LSL = 1.0
SPEC_TP_USL = 95.75
SPEC_TP_REF = 95.60
SPEC_TP_LSL = 95.45
SPEC_TW_USL = 45.15 
SPEC_TW_REF = 45.0
SPEC_TW_LSL = 44.85
SPEC_TS_USL = 14.05
SPEC_TS_REF = 13.15
SPEC_TS_LSL = 12.25


[MACHINE]
AUTO_ON_FUNCTION = "USE"
AUTO_ON_CHECK_TIME = 180
EPC_DIRECTION = 1
SCALE_READ_PLC = 100
SCALE_WRITE_PLC = 100
SCALE_WRITE_EPC = 1000
SCALE_WRITE_MOLD = 1000
GAIN_TCH = 0.4
GAIN_TP = 0.3
CONTROL_CYCLE_TCH = 82
CONTROL_CYCLE_TP = 66
GAIN_TCH_LC = 0.3
CONTROL_CYCLE_TCH_LC = 30 #20
OFFSET_TCH_LIMIT = 0.4
OFFSET_TP_LIMIT = 0.02
GATHER_TOL_EPC = 0.7
GATHER_TOL_TP = 0.35
PVAR_CRITERIA = 0.001
CMD_OFFSET_Y = 0
TYPE = "LASER"
TS_VISION_DATA = "TS"
